on:
  push:
    branches:
      - main
name: Build and Deploy Front-end on AWS
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create an .env file
        run: echo "REACT_APP_API_URL=${{secrets.REACT_APP_API_URL}}" > .env
      - name: Docker Compose Down
        run: docker compose down
      - name: Build
        run: docker compose build
      - name: Docker Compose Up
        run: docker compose up -d
